<?php

namespace CommonBundle\Repository;
use Doctrine\ORM\NoResultException;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllNews()
    {
        return $this->createQueryBuilder('n');
    }
}