homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:Index }

registration:
    path:     /register
    defaults: { _controller: FrontBundle:User:registration }

login:
    path:     /login
    defaults: { _controller: FrontBundle:User:login }

login_check:
    path:     /login_check
    defaults: { _controller: FrontBundle:User:login }

logout:
    path:     /logout
    defaults: { _controller: FrontBundle:User:logout }
