# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.form_login_authenticator:
        class: CommonBundle\Security\FormLoginAuthenticator
        arguments: ["@router", "@security.password_encoder"]
    app.access_denied_handler:
        class: CommonBundle\Security\AccessDeniedHandler